import { createContext } from "react-router";

// React Router 8 context: typed keys on a RouterContextProvider, set once in
// workers/app.ts and read in loaders/actions with context.get(...).
// Env is generated by `wrangler types` from wrangler.jsonc.
export const cloudflareContext = createContext<{
  env: Env;
  ctx: ExecutionContext;
}>();
